In [ ]:
# import the package
import nltk
import pandas as pd
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import os
sid = SentimentIntensityAnalyzer()

In [2]:
base_dir = "/Users/zejiachen/Desktop/fall 2021/QTM 340/Final Project/DataForAnalysis/"
# get a list of all the files in the directory
docs = os.listdir(base_dir)
docs.pop(1)

'.DS_Store'

In [5]:
# getting the file name
filmName = [os.path.splitext(os.path.basename(x))[0] for x in docs]
filmName

['interstellar',
 'inception',
 'tenet',
 'memento',
 'the-prestige',
 'the-dark-knight',
 'dunkirk-2017',
 'following',
 'insomnia-2002']

In [9]:
# read all the .csv file to dataframe
films = {}
for i in range(len(filmName)):
        films[filmName[i]] = pd.read_csv('/Users/zejiachen/Desktop/fall 2021/QTM 340/Final Project/DataForAnalysis/' + docs[i])

In [10]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.colheader_justify', 'center')
pd.set_option('display.precision', 3)

for film in films:
    print(film)
    display(films[film][:3])

interstellar

   Unnamed: 0 Rating                      Comments                       overall  negative  neutral  positive  compound
0       0      ★★★★★  I have a headache, but it's the best headache ...     5       0.000    0.608     0.392     0.778
1       1      ★★★★★  tell me you wouldn't cry too if your son grows...     5       0.000    0.846     0.154     0.372
2       2      ★★★★★  I'm pretty sure no one will EVER come close to...     5       0.178    0.594     0.227     0.226

inception

   Unnamed: 0 Rating                      Comments                       overall  negative  neutral  positive  compound
0       0      ★★★★★  "Inception," at its most basic, is two things....     5       0.000    0.849     0.151     0.926
1       1      ★★★★★  cillian murphy: no dad i'm giving up on YOUR d...     5       0.158    0.504     0.338     0.359
2       2      ★★★★½  christopher nolan spent years writing this mov...     4       0.000    1.000     0.000     0.000

tenet

   Unnamed: 0 Rating                      Comments                       overall  negative  neutral  positive  compound
0       0       ★★½                              thank you for watching     2       0.000    0.545     0.455     0.361
1       1         ★   Half the dialogue is exposition. The soundtrac...     1       0.079    0.921     0.000    -0.226
2       2         ½   nolan so scared to flop he designed a movie yo...     0       0.347    0.653     0.000    -0.706

memento

   Unnamed: 0 Rating                      Comments                       overall  negative  neutral  positive  compound
0       0      ★★★★½         this is what finding dory should have been     4       0.000    1.000     0.000     0.000
1       1       ★★★★       i love not knowing what the fuck is going on     4       0.238    0.476     0.286     0.178
2       2       ★★★★  me: [giving him the finger] test this, you fuc...     4       0.000    1.000     0.000     0.000

the-prestige

   Unnamed: 0 Rating                      Comments                       overall  negative  neutral  positive  compound
0       0      ★★★★½  Sometimes you just gotta ruin your life to own...     4       0.321    0.679      0.0     -0.688
1       1       ★★★★       when the prank war just goes too damn far :(     4       0.576    0.424      0.0     -0.859
2       2      ★★★★½  Second unexpected Radiohead in the credits mom...     4       0.000    0.800      0.2      0.361

the-dark-knight

   Unnamed: 0 Rating                      Comments                       overall  negative  neutral  positive  compound
0       0      ★★★★★  If you do not like this movie, I do not like you.     5       0.319    0.681     0.000    -0.497
1       1      ★★★★★         the best superhero movie ever made. period     5       0.000    0.588     0.412     0.637
2       2      ★★★★★                 has no right to still be this good     5       0.190    0.518     0.292     0.290

dunkirk-2017

   Unnamed: 0 Rating                      Comments                       overall  negative  neutral  positive  compound
0       0      ★★★★                 hans zimmer: TICK TOCK MOTHERFUCKER     4       0.571    0.429     0.000    -0.746
1       1       ★★★                         so thank you, harry styles.     3       0.000    0.589     0.411     0.420
2       2       ★★★   chris nolan: actually can I have 100 more of t...     3       0.000    1.000     0.000     0.000

following

   Unnamed: 0 Rating                      Comments                       overall  negative  neutral  positive  compound
0       0       ★★★   A Christopher Nolan movie where people swear a...     3       0.291    0.709      0.0     -0.477
1       1       ★★★                                     following on yt     3       0.000    1.000      0.0      0.000
2       2       ★★★                            Christopher Nolan Ranked     3       0.000    1.000      0.0      0.000

insomnia-2002

   Unnamed: 0 Rating                      Comments                       overall  negative  neutral  positive  compound
0       0      ★★★½                    could never happen to dunkaccino     3       0.000    1.000     0.000     0.000
1       1      ★★★½   The MTV Movie Awards should have created a "be...     3       0.261    0.418     0.321     0.178
2       2      ★★★★          oh mr nolan how very david fincher of you!     4       0.000    1.000     0.000     0.000

In [16]:
filmSentimentScore = dict.fromkeys(filmName)
colName = ['negative', 'neutral', 'positive']

for film in films:
    filmSentimentScore[film] = dict.fromkeys(['negative', 'neutral', 'positive', 'compound'])

In [17]:
# I am not sure if I am calculating this correctly
for film in films:
    for col in colName:
        filmSentimentScore[film][col] = round(films[film][col].mean(), 3)

In [ ]:
# calculating the mean compound score seperately
meanCompound = []

for film in filmName:
    print('film: ' + film)
    nrow = len(films[film].index)
    count = 0
    totalScores = sum(films[film]['compound'])
    print(film + ' TotalCompoundScore: ' + str(totalScores))
    for i in range(nrow):
        if films[film]['compound'][i] != 0:
            count += 1
    print('count: ' + str(count))
    filmSentimentScore[film]['compound'] = round(totalScores / count, 3)

In [19]:
filmSentimentScore

{'interstellar': {'negative': 0.091,
  'neutral': 0.735,
  'positive': 0.175,
  'compound': 0.244},
 'inception': {'negative': 0.054,
  'neutral': 0.763,
  'positive': 0.18,
  'compound': 0.348},
 'tenet': {'negative': 0.092,
  'neutral': 0.796,
  'positive': 0.112,
  'compound': 0.087},
 'memento': {'negative': 0.085,
  'neutral': 0.76,
  'positive': 0.153,
  'compound': 0.29},
 'the-prestige': {'negative': 0.094,
  'neutral': 0.757,
  'positive': 0.149,
  'compound': 0.246},
 'the-dark-knight': {'negative': 0.058,
  'neutral': 0.758,
  'positive': 0.183,
  'compound': 0.351},
 'dunkirk-2017': {'negative': 0.092,
  'neutral': 0.742,
  'positive': 0.165,
  'compound': 0.181},
 'following': {'negative': 0.059,
  'neutral': 0.775,
  'positive': 0.166,
  'compound': 0.405},
 'insomnia-2002': {'negative': 0.087,
  'neutral': 0.75,
  'positive': 0.162,
  'compound': 0.304}}

---
## Testing the VADER's Accuracy

Positive Review: 'overall' > 4 <br>
Negative Review: 'overall' < 3 <br>

What VADER's positive review: 'compound' > 0.35 <br>
What VADER's nagative review: 'compound' < 0 <br>
    
Reviews that both we and VADER think are a positive review: 'overall' > 4 & 'compound' > 0.35 <br>
Reviews that both we and VADER think are a negative review: 'overall' < 3.5 & 'compound' < 0

In [55]:

for film in filmName:
    percent = []
    name = films[film]
    colName = list(name)
    
    positive = len(name.loc[(name['overall'] > 4), colName])
    positiveVADER = len(name.loc[(name['compound'] > 0.35), colName])
    posIntersection = len(name.loc[(name['overall'] > 4) & (name['compound'] > 0.35), colName])

    
    negative = len(name.loc[(name['overall'] < 3), colName])
    negativeVADER = len(name.loc[(name['compound'] < 0), colName])
    negIntersection = len(name.loc[(name['overall'] < 3) & (name['compound'] < 0), colName])

    
    print(film)
    print('There are in total of ' + str(positive) + ' positive review')
    print('VADER thinks that there are ' + str(positiveVADER) + ' positive review')
    print('Reivews that both we and VADER think is a positive review: ' + str(posIntersection))
    print('Accuracy: ' + str(round(posIntersection / positive, 3)))
    
    print('There are in total of ' + str(negative) + ' negative review')
    print('VADER thinks that there are ' + str(negativeVADER) + ' negative review')
    print('Reivews that both we and VADER think is a negative review: ' + str(negIntersection))
    print('Accuracy: ' + str(round(negIntersection / negative, 3)))
    
    print()
    print()

interstellar
There are in total of 176 positive review
VADER thinks that there are 135 positive review
Reivews that both we and VADER think is a positive review: 85
Accuracy: 0.483
There are in total of 20 negative review
VADER thinks that there are 79 negative review
Reivews that both we and VADER think is a negative review: 6
Accuracy: 0.3


inception
There are in total of 231 positive review
VADER thinks that there are 160 positive review
Reivews that both we and VADER think is a positive review: 100
Accuracy: 0.433
There are in total of 8 negative review
VADER thinks that there are 54 negative review
Reivews that both we and VADER think is a negative review: 4
Accuracy: 0.5


tenet
There are in total of 34 positive review
VADER thinks that there are 68 positive review
Reivews that both we and VADER think is a positive review: 1
Accuracy: 0.029
There are in total of 59 negative review
VADER thinks that there are 67 negative review
Reivews that both we and VADER think is a negative review: 22
Accuracy: 0.373


memento
There are in total of 140 positive review
VADER thinks that there are 154 positive review
Reivews that both we and VADER think is a positive review: 63
Accuracy: 0.45
There are in total of 7 negative review
VADER thinks that there are 81 negative review
Reivews that both we and VADER think is a negative review: 4
Accuracy: 0.571


the-prestige
There are in total of 158 positive review
VADER thinks that there are 147 positive review
Reivews that both we and VADER think is a positive review: 76
Accuracy: 0.481
There are in total of 11 negative review
VADER thinks that there are 85 negative review
Reivews that both we and VADER think is a negative review: 4
Accuracy: 0.364


the-dark-knight
There are in total of 244 positive review
VADER thinks that there are 168 positive review
Reivews that both we and VADER think is a positive review: 116
Accuracy: 0.475
There are in total of 14 negative review
VADER thinks that there are 67 negative review
Reivews that both we and VADER think is a negative review: 8
Accuracy: 0.571


dunkirk-2017
There are in total of 123 positive review
VADER thinks that there are 119 positive review
Reivews that both we and VADER think is a positive review: 48
Accuracy: 0.39
There are in total of 17 negative review
VADER thinks that there are 89 negative review
Reivews that both we and VADER think is a negative review: 7
Accuracy: 0.412


following
There are in total of 5 positive review
VADER thinks that there are 201 positive review
Reivews that both we and VADER think is a positive review: 1
Accuracy: 0.2
There are in total of 54 negative review
VADER thinks that there are 65 negative review
Reivews that both we and VADER think is a negative review: 16
Accuracy: 0.296


insomnia-2002
There are in total of 8 positive review
VADER thinks that there are 147 positive review
Reivews that both we and VADER think is a positive review: 4
Accuracy: 0.5
There are in total of 33 negative review
VADER thinks that there are 73 negative review
Reivews that both we and VADER think is a negative review: 15
Accuracy: 0.455

---
## Tf-Idf

In [65]:
mostPosReviews = {}
for film in films:
    mostPosReviews[film] = pd.DataFrame(films[film].loc[(films[film]['overall'] > 4), ['Comments', 'overall']])
    mostPosReviews[film].columns = ['Comments', 'overall']
    
mostNegReviews = {}
for film in films:
    mostNegReviews[film] = pd.DataFrame(films[film].loc[(films[film]['overall'] < 3), ['Comments', 'overall']])
    mostNegReviews[film].columns = ['Comments', 'overall']

In [70]:
mostPosReviewsList = []
i = 0
for review in mostPosReviews:
    mostPosReviewsList.append(mostPosReviews[review]['Comments'].tolist())
    i += 1
    
mostNegReviewsList = []
j = 0
for review in mostNegReviews:
    mostNegReviewsList.append(mostNegReviews[review]['Comments'].tolist())
    j += 1

In [69]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [73]:
english_stemmer = nltk.stem.SnowballStemmer('english')

class StemmedTfidfCountVectorizer(TfidfVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedTfidfCountVectorizer, self).build_analyzer()
        return lambda doc: ([english_stemmer.stem(w) for w in analyzer(doc)])

### Positive Matrix

In [99]:
# create matrix for each of the film
tfidf_vectorizer=StemmedTfidfCountVectorizer(stop_words='english', use_idf=True) # excludings stopwords again
 
mostPosReviewsMatrix = {}
x = 0
for i in mostPosReviewsList:
    tfidf_vectorizer_vectors=tfidf_vectorizer.fit_transform(i)
    mostPosReviewsMatrix[filmName[x]] = pd.DataFrame(tfidf_vectorizer_vectors.toarray(), columns=tfidf_vectorizer.get_feature_names())
    x += 1

In [93]:
top_dict_pos = {}
for film in filmName:
    nReview = len(mostPosReviewsMatrix[film].index)
    data = mostPosReviewsMatrix[film].transpose()
    for c in range(nReview):
        top = data.iloc[:,c].sort_values(ascending = False).head(30)
        top_dict_pos[film] = list(zip(top.index, top.values))

In [87]:
# Print the top 15 words said by positive reviews
for film, top_words in top_dict_pos.items():
    print(film)
    print(', '.join([word for word, count in top_words[0:9]]))
    print('---')

interstellar
3rd, view, fantast, fi, fell, feel, feat, feast, favourit
---
inception
forgot, concern, long, far, ve, way, favorit, seen, masterpiec
---
tenet
dream, sail, coast, amalfi, yacht, life, debicki, elizabeth, entir
---
memento
like, modern, tragedi, ithaca, ulyss, travel, ancient, greek, homer
---
the-prestige
terrifi, magic, fail, favorit, fast, fascin, farewel, far, fantast
---
the-dark-knight
10, zimmer, favourit, find, final, filmmak, film, fight, fiftieth
---
dunkirk-2017
weymouth, spitfir, paparazzi, prop, crew, holiday, set, flex, fli
---
following
nolan, intrigu, tens, nonlinear, fantast, high, good, follow, fit
---
insomnia-2002
pacino, al, anxieti, chew, cure, gum, good, film, filmmak
---

**Try bi-gram**

In [89]:
# create matrix for each of the film
tfidf_vectorizerBigram=StemmedTfidfCountVectorizer(stop_words='english', use_idf=True, ngram_range = (2, 2)) 
 
mostPosReviewsBigramMatrix = {}
x = 0
for i in mostPosReviewsList:
    tfidf_vectorizer_vectors_bigram=tfidf_vectorizerBigram.fit_transform(i)
    mostPosReviewsBigramMatrix[filmName[x]] = pd.DataFrame(tfidf_vectorizer_vectors_bigram.toarray(), columns=tfidf_vectorizerBigram.get_feature_names())
    x += 1

In [94]:
top_dict_pos_bigram = {}
for film in filmName:
    nReview = len(mostPosReviewsBigramMatrix[film].index)
    data = mostPosReviewsBigramMatrix[film].transpose()
    for c in range(nReview):
        top = data.iloc[:,c].sort_values(ascending = False).head(30)
        top_dict_pos_bigram[film] = list(zip(top.index, top.values))

In [95]:
# Print the top 15 words said by positive reviews
for film, top_words in top_dict_pos_bigram.items():
    print(film)
    print(', '.join([word for word, count in top_words[0:9]]))
    print('---')

interstellar
3rd view, zoop movi, galaxy brain, gates heaven, gave amaz, generation hop, generational mort, generations com, genius reinv
---
inception
far concern, way long, favorites arthur, concerned favorit, loved masterpiec, movie forgot, long v, forgot lov, masterpiece far
---
tenet
yacht elizabeth, dream lif, debicki amalfi, amalfi coast, sail yacht, life sail, elizabeth debicki, fuck star, fun cowboy
---
memento
like modern, favorite movi, like kavafi, like anci, ends lik, memories lik, probably favorit, modern hom, modern ulyss
---
the-prestige
magic terrifi, youtu hloxr9ejqjq, film us, flaws whatsoev, forces audi, forget dark, forget incept, fraud sequenti, fresh ey
---
the-dark-knight
zimmer us, god heath, godlike symbol, going soon, gone hand, gone soon, good 2021, good act, good dc
---
dunkirk-2017
saw movi, boats set, paparazzi near, seen spitfir, times fli, videos prop, weymouth lik, weymouth holiday, weymouth harbour
---
following
intriguing nolan, tense nonlinear, nolan nolan, nonlinear intrigu, watching debut, film debut, just fantast, highly recommend, good perform
---
insomnia-2002
pacino chew, cure anxieti, al pacino, chewing gum, gum cur, floodlights good, genres experi, good film, good measur
---

### Negative Matrix

In [101]:
mostNegReviewsMatrix = {}
x = 0
for i in mostNegReviewsList:
    tfidf_vectorizer_vectors=tfidf_vectorizer.fit_transform(i)
    mostNegReviewsMatrix[filmName[x]] = pd.DataFrame(tfidf_vectorizer_vectors.toarray(), columns=tfidf_vectorizer.get_feature_names())
    x += 1
    

top_dict_neg = {}
for film in filmName:
    nReview = len(mostNegReviewsMatrix[film].index)
    data = mostNegReviewsMatrix[film].transpose()
    for c in range(nReview):
        top = data.iloc[:,c].sort_values(ascending = False).head(30)
        top_dict_neg[film] = list(zip(top.index, top.values))

In [103]:
# Print the top 15 words said by positive reviews
for film, top_words in top_dict_neg.items():
    print(film)
    print(', '.join([word for word, count in top_words[0:9]]))
    print('---')

interstellar
susskind, wrong, christoph, astrophysicist, leonard, assert, ve, fame, seen
---
inception
paprika, mal, hecha, addit, engin, disguis, disjoint, don, draw
---
tenet
hell, great, cinematographi, confus, zero, fortnit, flop, focus, fool
---
memento
reddit, masturb, heterosexu, vandal, grant, film, forget, fuck, get
---
the-prestige
zero, wrong, don, downright, eeri, end, fall, featur, feel
---
the-dark-knight
hyperbol, clunki, dialogu, edit, contrarian, statement, drop, time, tri
---
dunkirk-2017
just, thirsti, big, bitch, style, countless, harri, twink, deal
---
following
anymor, fincher, bro, peopl, make, good, film, nolan, dump
---
insomnia-2002
meh, yogurt, fall, generic, gave, frogger, finish, fincher, filmographi
---

**Try Bi-gram**

In [104]:
mostNegReviewsBigramMatrix = {}
x = 0
for i in mostNegReviewsList:
    tfidf_vectorizer_vectors_bigram=tfidf_vectorizerBigram.fit_transform(i)
    mostNegReviewsBigramMatrix[filmName[x]] = pd.DataFrame(tfidf_vectorizer_vectors_bigram.toarray(), columns=tfidf_vectorizerBigram.get_feature_names())
    x += 1
    
top_dict_neg_bigram = {}
for film in filmName:
    nReview = len(mostNegReviewsBigramMatrix[film].index)
    data = mostNegReviewsBigramMatrix[film].transpose()
    for c in range(nReview):
        top = data.iloc[:,c].sort_values(ascending = False).head(30)
        top_dict_neg_bigram[film] = list(zip(top.index, top.values))

In [105]:
# Print the top 15 words said by positive reviews
for film, top_words in top_dict_neg_bigram.items():
    print(film)
    print(', '.join([word for word, count in top_words[0:9]]))
    print('---')

interstellar
astrophysicist christoph, seen year, movie v, asserts leonard, ve seen, nolan assert, famed astrophysicist, susskind wrong, leonard susskind
---
inception
mal hecha, paprika m, hates wif, hair way, development mishmash, dicaprio spectacular, disguised subject, disjointed deriv, don wish
---
tenet
great cinematographi, cinematography confus, confusing hel, years mf, gay charact, forgot immedi, forgot tel, forgot upload, fucken audio
---
memento
heterosexuals reddit, reddit masturb, vandalized bodi, events piec, joe pantoliano, instructions fact, insincerity speak, inciting incid, incident effect
---
the-prestige
zero cinemat, don hel, downright eeri, eerie actor, ending rev, fall clev, features ricki, feel fre, feels meticul
---
the-dark-knight
dialogue clunki, times edit, just tdk, films rec, overrated film, editing dialogu, drop hyperbol, recent tim, contrarian drop
---
dunkirk-2017
styles just, big deal, thirsty harri, just thirsti, just countless, twink bitch, countless twink, bitches big, harry styl
---
following
good film, make good, bro peopl, films anymor, nolan finch, people mak, anymore nolan, film th, filmmaker mak
---
insomnia-2002
yogurt director, filmography tenet, guess expect, gruff dog, great worth, great sceneri, great punchlin, great perform, good way
---

---
## Prediction All

In [2]:
filmNolan = pd.read_csv('/Users/zejiachen/Desktop/fall 2021/QTM 340/Final Project/filmNolan.csv')

In [3]:
filmNolan.head()

,Unnamed: 0,Film,Rating,Comments,overall,negative,neutral,positive,compound
0,0,interstellar,★★★★★,"I have a headache, but it's the best headache ...",5,0.000,0.608,0.392,0.7783
1,1,interstellar,★★★★★,tell me you wouldn't cry too if your son grows...,5,0.000,0.846,0.154,0.3724
2,2,interstellar,★★★★★,I'm pretty sure no one will EVER come close to...,5,0.178,0.594,0.227,0.2263
3,3,interstellar,★★★★,When those Zimmer organs kick in *biggest poss...,4,0.000,1.000,0.000,0.0000
4,4,interstellar,★★★★★,i needed a REALLY good cry,5,0.407,0.200,0.393,-0.0384

In [7]:

positiveAll = len(filmNolan.loc[(filmNolan['overall'] > 4)])
positiveVADERAll = len(filmNolan.loc[(filmNolan['compound'] > 0.35)])
posIntersectionAll = len(filmNolan.loc[(filmNolan['overall'] > 4) & (filmNolan['compound'] > 0.35)])


negativeAll = len(filmNolan.loc[(filmNolan['overall'] < 3)])
negativeVADERAll = len(filmNolan.loc[(filmNolan['compound'] < 0)])
negIntersectionAll = len(filmNolan.loc[(filmNolan['overall'] < 3) & (filmNolan['compound'] < 0)])



print('There are in total of ' + str(positiveAll) + ' positive review')
print('VADER thinks that there are ' + str(positiveVADERAll) + ' positive review')
print('Reivews that both we and VADER think is a positive review: ' + str(posIntersectionAll))
print('Accuracy: ' + str(round(posIntersectionAll / positiveAll, 3)))

print('There are in total of ' + str(negativeAll) + ' negative review')
print('VADER thinks that there are ' + str(negativeVADERAll) + ' negative review')
print('Reivews that both we and VADER think is a negative review: ' + str(negIntersectionAll))
print('Accuracy: ' + str(round(negIntersectionAll / negativeAll, 3)))

print()
print()

There are in total of 1119 positive review
VADER thinks that there are 1299 positive review
Reivews that both we and VADER think is a positive review: 494
Accuracy: 0.441
There are in total of 223 negative review
VADER thinks that there are 660 negative review
Reivews that both we and VADER think is a negative review: 86
Accuracy: 0.386